### ISSUE TITLE
Diagrams and Visuals Tracking

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#43]
# Diagrams and Visuals Tracking

## Diagrams we need `P3`

 - [ ] Visual depicting difference between the parachains and relay chains (shown as blocks)
 - [ ] Diagram of Validator and Collator when validating a state transition against a STF
 - [ ] Diagram of Interchain communication (shown as blocks) something like below with the relay chain in the middle and the parachains around it, showing how a message will originate on one parachain and be places in the input queue of another.
![](https://media.nature.com/m685/nature-assets/ncomms/2014/140129/ncomms4119/images_hires/ncomms4119-f1.jpg)
 - [ ] Parachain auction diagram. Currently we have some [ascii art](http://wiki.polkadot.network/en/latest/polkadot/learn/candle/#how-does-bidding-work), but there exists a diagram used in presentation. Maybe we can use or update the diagram?
- [ ] Break apart the below complex image from the whitepaper into more digestible parts.
![](https://camo.githubusercontent.com/dd327c791d3aa33ab4badd5336bfd2649ec82cb5/68747470733a2f2f692e696d6775722e636f6d2f613873794b67422e706e67)
- [ ] [This image](https://camo.githubusercontent.com/3aff4631070a69c805d4c5e8ae89bc13e4ea393e/68747470733a2f2f692e696d6775722e636f6d2f6f33773430365a2e706e67) that outlines different traits of solo chains, parachains, and bridges looks like its a screen grab from the old website. Evaluate: Do we update?

## Examples / Ideas

- There are some Substrate / Polkadot related diagrams collected already in [awesome-substrate](https://github.com/nczhu/awesome-substrate#helpful-diagrams). We should re-use these or determine if any should be updated by Iggy.
- Substrate docs for [Architecture of a Runtime](https://docs.substrate.dev/docs/architecture-of-a-runtime) has a diagram which is also clickable, allowing users to explore the architecture interactively.  We can do something similar for Polkadot, where each layer of the stack is its own diagram with clickable parts. This could be something like a sitemap where it exists on its own page or it could be including on every relevant page.

**Comment by ansonla3** [comment]
https://hackmd.io/2p584XMRQiyXLFaJgBZJtw?both

**Comment by lsaether** [comment]
Helpful info when requesting a new image:

- Search for the image if it already exists. If not, try to find one like it and say what will be new or different.
- Find reference images (could be from other domains such as biology).
- Divide the graphics in steps. Describe each step.
