### ISSUE TITLE
Milestone: Deprecating the older Polkadot wiki

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#54]
Tracking issue for the tasks that should be done before we fully deprecate the Polkadot GH wiki (ie the [old one](https://github.com/paritytech/polkadot/wiki))

- [X] DOT
- [ ] Governance **included in next PR #56**
- [X] Moving from PoC1 to PoC2 **outdated: not needed**
- [X] Parachains
- [ ] Polkadot Extrinsics Format #56
- [X] Polkadot Roles and Actors **Spread across the node operators pages**
- [X] Polkadot UI
- [ ] ?Style Guide **Can be added to the wiki but I feel this should be part of the README of Polkadot repository instead** #56
- [X] ~Validating on PoC1~ **outdated: not needed**
- [X] ~Validating on PoC2~ **outdated: not needed**
- [X] Validating on PoC3 "Alexander"

Once these pages have been migrated over we may place a **deprecation** notice on the old pages and redirect to the new pages.
